name: ${name}
version: ${version}
website: ${url}
authors: ["${author}"]
main: net.paradisu.bukkit.ParadisuMain
api-version: 1.19
commands:
  dbconnect:
    description: connects to db
  reloadshops:
    description: reloads shops
  getshop:
    description: gets shop
  reloadhats:
    description: reload hat config
  reloadprops:
     description: reload prop config