name: ${name}
version: ${version}
website: ${url}
authors: [${authors}]
main: net.paradisu.bukkit.ParadisuMain
api-version: ${spigotApiVersion}
commands:
  dbconnect:
    description: connects to db
  reloadshops:
    description: reloads shops
  getshop:
    description: gets shop
  reloadhats:
    description: reload hat config
  reloadprops:
     description: reload prop config