name: ParadisuPlugin
version: ${minecraft.plugin.version}
authors: [JJakee, cytocracy, _Kastle, CookieCrafted]
main: net.paradisu.bukkit.ParadisuMain
api-version: 1.18
commands:
  dbconnect:
    description: connects to db
  reloadshops:
    description: reloads shops
  getshop:
    description: gets shop
  reloadhats:
    description: reload hat config
  reloadprops:
     description: reload prop config