name: Build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/*.yml'
      - '.github/workflows/build.yml'
      - '.github/workflows/pull-request.yml'
      - '.gitignore'
      - .devcontainer/devcontainer.json
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
        release_id: ${{ steps.release.outputs.releaseID }}
    steps:
    - name: Checkout Repository and Submodules
      # See https://github.com/actions/checkout/releases
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        submodules: recursive
    - name: Set up JDK 21
      # See https://github.com/actions/setup-java/releases
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        java-version: 21
        distribution: temurin
    - name: Setup Gradle
      # See https://github.com/gradle/actions/releases
      uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b
    - name: Build with Gradle
      run: ./gradlew build
    - name: Archive Artifacts
      # See https://github.com/actions/upload-artifact/releases
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      if: success()
      with:
        name: ParadisuPlugin
        path: build/libs/ParadisuPlugin.jar
        if-no-files-found: error
    - name: Create Release
      # See https://github.com/Kas-tle/base-release-action/releases
      uses: Kas-tle/base-release-action@65d06f835be34757c6d73c16959c97e92c2a3c7f
      if: ${{ success() && github.repository == 'Paradisu/ParadisuPlugin' }}
      id: release
      with:
        files: |
          build/libs/ParadisuPlugin.jar
        appID: ${{ secrets.RELEASE_APP_ID }}
        appPrivateKey: ${{ secrets.RELEASE_APP_PK }}
        preRelease: ${{ github.ref_name != 'master' }}
        discordWebhook: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Setup NodeJS
      # See https://github.com/actions/setup-node/releases
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
      if: ${{ success() && github.repository == 'Paradisu/ParadisuPlugin' && github.ref_name == 'master' }}
    - name: Publish Plugin to Servers
      if: ${{ success() && github.repository == 'Paradisu/ParadisuPlugin' && github.ref_name == 'master' }}
      env:
        PTEROPUB_CONFIG: ${{ secrets.PTEROPUB_CONFIG }}
      run: npx pteropub
  upload-logs:
    name: Upload Logs
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Upload Logs
      # See https://github.com/Kas-tle/release-build-log-action/releases
      if: ${{ success() && github.repository == 'Paradisu/ParadisuPlugin' }}
      uses: Kas-tle/release-build-log-action@1b57448eaf9476e6e05450e4ea240449eac2c0d2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        releaseID: ${{ needs.build.outputs.release_id }}