name: Build Remote

on:
  workflow_call:
    inputs:
      repository:
        required: true
        description: 'The repo of the remote'
        type: string
      ref:
        required: true
        description: 'The ref of the remote'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository and Submodules
      # See https://github.com/actions/checkout/releases
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        submodules: recursive
    - name: Validate Gradle Wrapper
      # See https://github.com/gradle/actions/releases
      uses: gradle/actions/wrapper-validation@db19848a5fa7950289d3668fb053140cf3028d43 # v3.3.2
    - name: Set up JDK 17
      # See https://github.com/actions/setup-java/releases
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
      with:
        java-version: 17
        distribution: temurin
    - name: Build with Gradle
      # See https://github.com/gradle/actions/releases
      uses: gradle/actions/setup-gradle@db19848a5fa7950289d3668fb053140cf3028d43 # v3.3.2
      with:
        arguments: build
        gradle-home-cache-cleanup: true
    - name: Archive Artifacts
      # See https://github.com/actions/upload-artifact/releases
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      if: success()
      with:
        name: ParadisuPlugin
        path: build/libs/ParadisuPlugin.jar
        if-no-files-found: error