name: Deploy Plungin

on:
    push:
        branches:
            - "master"
        paths:
            - "gradle.properties"

jobs:
  validate-version:
    name: Validate Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get previous tag
        id: getPreviousTag
        uses: WyriHaximus/github-action-get-previous-tag@v1
      - name: Validate Version
        env:
          PREVIOUS_VERSION: ${{ steps.getPreviousTag.outputs.tag }}
        run: |
          CURRENT_VERSION=$(cat gradle.properties | grep "version" | cut -d'=' -f2)
          PREV_VER_GEQ_CUR_VER=$(
            jq -r -n --arg previous_version "${PREVIOUS_VERSION}" --arg current_version "${CURRENT_VERSION}" '
            def ver2arr($inp): ($inp | split(".") | map(tonumber)); 
              ver2arr($previous_version) as $ver_prev  
            | ver2arr($current_version) as $ver_cur 
            | if ($ver_prev[0] > $ver_cur[0]) or ($ver_prev[1] > $ver_cur[1] and $ver_cur[1] != 0) or ($ver_prev[2] >= $ver_cur[2] and $ver_cur[2] != 0) then true else false end
          ')
          if [ "${PREV_VER_GEQ_CUR_VER}" = true ]; then
            echo "Previous version is greater than or equal to current version."
            echo "Please update gradle.properties with a valid SemVer version greater than ${PREVIOUS_VERSION} before pushing again!"
            exit 1
          fi
  build:
    runs-on: ubuntu-latest
    needs: [validate-version]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get previous version
      id: getPreviousTag
      uses: WyriHaximus/github-action-get-previous-tag@v1
    - name: Get current version
      id: lookupParadisuVersion
      run: echo result=$(cat gradle.properties | grep "version" | cut -d'=' -f2) >> $GITHUB_OUTPUT
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ''
        custom_tag: ${{ steps.lookupParadisuVersion.outputs.result }}
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        gradle-home-cache-cleanup: true
    - run: mkdir staging && cp build/libs/ParadisuPlugin.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: ParadisuPlugin-Latest
        path: staging/ParadisuPlugin.jar
    - name: Generate release diff
      env:
        BEGIN_COMMIT: ${{ steps.getPreviousTag.outputs.tag }}
        END_COMMIT: ${{ steps.lookupParadisuVersion.outputs.result }}
      run: git fetch --tags --force && git log --pretty=format:"* %s (%h)" ${BEGIN_COMMIT}..${END_COMMIT} > release_notes.md
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: staging/ParadisuPlugin.jar
        allowUpdates: true
        bodyFile: "release_notes.md"
        draft: false
        prerelease: false
        tag: ${{ steps.lookupParadisuVersion.outputs.result }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload jar to server
      env:
        PTERODACTYL_TOKEN: ${{ secrets.PTERODACTYL_TOKEN }}
      run: |
        cp staging/ParadisuPlugin.jar ParadisuPlugin.jar
        upload_plugin () {
          local upload_url=$(curl "https://panel.paradisu.net/api/client/servers/${1}/files/upload" -H "Authorization: Bearer ${PTERODACTYL_TOKEN}" -X GET -s | jq -r .attributes.url)
          curl -F files=@ParadisuPlugin.jar "${upload_url}&directory=/plugins"
        }
        restart_server () {
          task_id=$(curl "https://panel.paradisu.net/api/client/servers/${1}/schedules" -H 'Accept: application/json' -H 'Content-Type: application/json' -H "Authorization: Bearer ${PTERODACTYL_TOKEN}" -X GET | jq '.data[]?.attributes? | select(.name == "Maintenance Restart") | .id')
          curl "https://panel.paradisu.net/api/client/servers/${1}/schedules/${task_id}/execute" -H 'Accept: application/json' -H 'Content-Type: application/json' -H "Authorization: Bearer ${PTERODACTYL_TOKEN}" -X POST
        }
        server_ids=(
          "978fd706"
          "1b063a16"
          "a0638f52"
          "517d0585"
        )
        for id in ${server_ids[@]}
        do
          upload_plugin ${id}
          restart_server ${id}
        done
