name: Process Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Repository and Submodules
      # See https://github.com/actions/checkout/releases
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        submodules: recursive
    - name: Set up JDK
      # See https://github.com/actions/setup-java/releases
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
      with:
        java-version: 25
        distribution: temurin
    - name: Setup Gradle
      # See https://github.com/gradle/actions/releases
      uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e
    - name: Build with Gradle
      run: ./gradlew build
    - name: Archive Artifacts
      # See https://github.com/actions/upload-artifact/releases
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
      if: success()
      with:
        name: ParadisuPlugin
        path: build/libs/ParadisuPlugin.jar
        if-no-files-found: error
    - name: Check Spotless Formatting
      run: ./gradlew spotlessCheck