name: Process Pull Request

on:
  pull_request_target:

jobs:
  build:
    # Forbid access to secrets nor GH Token perms while building the PR
    permissions: {}
    secrets: {}
    uses: ./.github/workflows/build-remote.yml
    with:
      repository: ${{ github.event.pull_request.head.repo.full_name }}
      ref: ${{ github.event.pull_request.head.sha }}